world: "spawn"
region: "pool"
time: 600 # Время сколько нужно стоять (в секундах)
ruble_reward: 25 # Награда в рублях (PlayerPoints)
period: 6 # Время через которое будет обновляться прогресс (в секундах)